host:                           'localhost'
port:                           '3010'
prefix:                         '/api/v1/'
protocol:                       'http'
nlims_default_username:         'admin'
nlims_default_password:         'knock_knock'
partner:                        'BHT'
app_name:                       'lab_test'
nlims_custome_password:         'lab_test'
nlims_custome_username:         'lab_test'
